version: '3.1'

services:
  db:
    image: mysql:8.0.21
    command: mysqld --init-file="/docker-entrypoint-initdb.d/init.sql"
    ports:
      - "30000:3306"
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example
    volumes:
      - ./db:/docker-entrypoint-initdb.d/:ro
      - ./data:/data

  app:
    build: ./app
    depends_on:
      - db
    ports:
      - "5000:5000"