version: "3.5"

services:
  postgres-db:
    image: postgres:12.4
    restart: always
    volumes:
      - ./.postgres-data:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - 5432:5432
    env_file:
      - ./.env

  app:
    build: ./app
    command: |
      python /app/data_loader.py
        --host postgres-db
        --port 5432
        --user ${POSTGRES_USER}
        --database ${POSTGRES_DB}
        --password ${POSTGRES_PASSWORD}
        --input-file /data/email.json.gz
        --error-file /data/error_records.txt
        --insert-batch-size 10000
    depends_on:
      - postgres-db
    volumes:
      - ./app:/app
      - ./data:/data
